### ISSUE TITLE
ListView load url into ImageView OutOfMemoryError

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [JakeWharton/picasso2-okhttp3-downloader#11]
java.lang.OutOfMemoryError: Could not allocate JNI Env
                                                               at java.lang.Thread.nativeCreate(Native Method)
                                                               at java.lang.Thread.start(Thread.java:1063)
                                                               at com.squareup.picasso.Picasso.<init>(Picasso.java:201)
                                                               at com.squareup.picasso.Picasso$Builder.build(Picasso.java:848)

If not using picasso2-okhttp3-downloader is normal

**Comment by JakeWharton** [comment]
This is not caused by this library directly which is just a simple shim. The stacktrace seems to indicate that your system is unable to start new threads.

**Comment by AndroidJohnsonWang** [comment]
Thanks, I've already solved the problem.
