### ISSUE TITLE
java.lang.NoClassDefFoundError using Donwloader

### ISSUE THREAD

**Issue by spiralni** [JakeWharton/picasso2-okhttp3-downloader#14]
I am using a custom downloader por Picasso.

```
 private PicassoCache (Context context)  {

        Downloader downloader   = new OkHttpDownloader(context, Integer.MAX_VALUE);
        Picasso.Builder builder = new Picasso.Builder(context);
        builder.downloader(downloader);

        picassoInstance = builder.build();
    }
```
gradle 

`compile 'com.squareup.okhttp3:okhttp:3.2.0'`
`compile 'com.squareup.okio:okio:1.10.0'`
`compile 'com.squareup.picasso:picasso:2.5.2'`
`compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2'`

But no matter what I do, I always have this error:

```
 stack=java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/OkHttpClient;
             at com.squareup.picasso.OkHttpDownloader.defaultOkHttpClient(OkHttpDownloader.java:31)
             at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:76)
             at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:65)
             at ni.com.spiralni.help.utils.PicassoCache.<init>(PicassoCache.java:27)
             at ni.com.spiralni.help.utils.PicassoCache.getPicassoInstance(PicassoCache.java:43)
             at ni.com.spiralni.help.utils.ImageUtils.setImageFromWebStorage(ImageUtils.java:34)
             at ni.com.spiralni.help.adapter.SearchResultListRVAdapter.onBindViewHolder(SearchResultListRVAdapter.java:45)
             at ni.com.spiralni.help.adapter.SearchResultListRVAdapter.onBindViewHolder(SearchResultListRVAdapter.java:24)
```

Is there any issue with this integration?

**Comment by JakeWharton** [comment]
Use OkHttp3Downloader instead of OkHttpDownloader when creating your
Picasso.Builder.

**Comment by spiralni** [comment]
Thanks,

I did try changing to OkHttp3Downloader  and using ` compile 'com.squareup.okhttp3:okhttp:3.4.1'`

and the problem persists.

After tried a lot of combinations I found this:

```
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
```

Thanks for your time.

**Comment by nishsvn-dev** [comment]
Upon using OkHttp3Downloader, the issue solved for me.

**Comment by shantanu0323** [comment]
Thank you so much sir... I was really stuck at it for a long time....

**Comment by sivasaravananrdm** [comment]
Thank you so much. the issue solved for me.
